# Generated by Django 5.1.7 on 2025-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Department', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('DOB', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
